### ISSUE TITLE
All Results Say "Fastest"

### ISSUE THREAD

**Issue by johnaweiss** [psiho/jsbench-me#42] opened 2021-02-13 00:24 UTC
https://jsbench.me/i2kkzuk4kl/1

**Comment by psiho** [comment] 2021-02-22 21:49
This is by design (of benchmark.js library used) and also correct. It happens when 2 or more test cases are equally fast (*by a margin of error* calculated by benchmark.js). If those are also fastest in the bunch, they will all be marked as fastest.

So, point is in margin of error. If difference in test speeds is smaller than % of error, it is impossible to be sure which one is faster. Also it is unimportant in practice, as difference is marginal.

**Closed by psiho** 2021-02-22 21:49 UTC
