### ISSUE TITLE
Safari Browser Setup JS Bug

### ISSUE THREAD

**Issue by akcorp2003** [psiho/jsbench-me#35] opened 2020-10-08 18:32 UTC
The area to add test cases for JS is not working and returning "IndexSizeError: The index is not in the allowed range" coming from `getRangeAt` in `codejar.js:171`.
![image](https://user-images.githubusercontent.com/12402936/95499211-d11cd880-0959-11eb-99eb-f26db6ae83a5.png)

This is on Safari v14.0 (15610.1.28.1.9, 15610).

However, the text box works for Setup JS.

**Comment by psiho** [comment] 2020-10-08 19:43
Textbox is a fallback option, but far from optimal. I haven't tested Safari at all. It's really hard for me to get my hands on a Mac. But it seems I'll have to try as this is a serious issue for Safari users.

**Comment by psiho** [comment] 2020-10-08 19:55
Well, I managed to reproduce the problem on Midori browser on Linux which is also a WebKit browser like Safari. So I have something to work on.

**Comment by terrymorse58** [comment] 2021-02-24 17:18
Bug confirmed in Safari Technology Preview, Release 120 (Safari 14.2).

The test case code sections are not selectable. I noticed the following styling:
```
-webkit-user-select: none;
```

Changing that to:
```
-webkit-user-select: text;
```

made the text in the code section selectable, and the select cursor appeared where the text was clicked. Typing still didn't work.

**Comment by psiho** [comment] 2021-02-24 21:33
Np. As mentioned earlier, it's finally easy for me to reproduce it on Linux. v1.1 update will start soon and this is high on the list https://github.com/psiho/jsbench-me/projects/2

**Comment by psiho** [comment] 2021-04-27 19:48
Yes, -webkit-user-select: text; was a solution. Not sure why it wasn't working for you. However, I did change it on more than one place.

Cause of this was latest drag&drop code for reordering suite cases. Somehow, draggable textboxes are useless on webkit browsers without this addition in css.

Since I tested this on Midori/Linux (as I don't have Apple stuff), here is a development location test url for any Apple users to check: https://dev--jsbenchme-v1.netlify.app/

**Comment by terrymorse58** [comment] 2021-04-27 20:07
I confirm that on the development site, the code boxes are selectable and editable on Safari (Mac OS).

- 
terry morse
***@***.***

**Comment by akcorp2003** [comment] 2021-04-27 23:49
I also can confirm that the text areas are selectable and editable on Safari. This is very exciting!

Minor note: I see the syntax highlighting doesn't work as I type but if I copied and pasted code, the highlighting comes back.
![image](https://user-images.githubusercontent.com/12402936/116326149-97d27b80-a778-11eb-85d5-91966d2df675.png)

**Comment by psiho** [comment] 2021-04-28 10:18
@akcorp2003 thx for noticing this. CodeJar update from 3.0.0 to 3.4.0. caused this new issue. Since this is a minor update, I rolled back for now and will update later. Change is not published on dev yet but will be fixed on release.

I'm closing this now.

**Closed by psiho** 2021-04-28 10:18 UTC
Labels: bug
