### ISSUE TITLE
What to do if my setup code is larger than allowed?

### ISSUE THREAD

**Issue by teetotum** [psiho/jsbench-me#47] opened 2021-07-22 15:51 UTC
I wanted to benchmark all proposed solutions for [pretty printing xml with javascript](https://stackoverflow.com/questions/376373/pretty-printing-xml-with-javascript); which results in quite a large "Setup JavaScript" field.
So what can I do to be able to save the benchmark and to share it in the stackoverflow discussion?
![image](https://user-images.githubusercontent.com/14925083/126669011-7c143ca3-56b5-4150-be5c-2a891f07d4b3.png)

**Comment by psiho** [comment] 2021-07-22 16:42
As discussed earleir: #24 ... I'm very sorry but this limitation is by design. I increased it in the last release and there is a good chance I'll increase it again in the next one. But for the time being, it is a feature that might affect AWS costs, and we're on the edge (and passed it before v1 optimizations) to go over AWS free tier limits so I'm being careful.

I might be over-optimizing here, I'll need to see stats of how last increase of limits affected AWS costs but there's no way back once I do it so I'm careful. It's a free project with no sponsors, and while I don't mind spending my time and a little bit of money, I really don't need monthly invoice for it :)

Check back in a few months. Decision will be made for the next release.

**Comment by psiho** [comment] 2023-04-02 14:12
It's been loooong time, but finally I'm closing this and unfortunately keeping the limit. AWS free tier is being broken every month now, usage and costs are rising.

General plan is to get rid of most AWS parts (API, Lambda, DynamoDB) and keep only Cognito. I will migrate to something simpler like local Postgres/Nodejs or similar. But it is too much work to make it in v1.2, so I'm postponing it.

**Closed by psiho** 2023-04-02 14:12 UTC
Labels: new feature
